# Generated by Django 3.2.4 on 2024-06-28 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
