# Generated by Django 3.2.4 on 2024-06-28 18:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0002_auto_20240628_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 18, 44, 55, 860830, tzinfo=utc)),
        ),
    ]
