# Generated by Django 3.2.4 on 2024-06-30 02:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembership',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 2, 54, 55, 833786, tzinfo=utc)),
        ),
    ]
