# Generated by Django 3.2.4 on 2024-07-03 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_auto_20240630_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 4, 50, 48, 660471, tzinfo=utc)),
        ),
    ]
