# Generated by Django 3.2.4 on 2024-07-05 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_alter_invitation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 22, 28, 14, 715464, tzinfo=utc)),
        ),
    ]
