# Generated by Django 3.2.4 on 2024-07-05 22:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0010_alter_invitation_expiry_date'),
        ('task', '0002_task_family'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificatiions',
            new_name='Notifications',
        ),
    ]
